import {z} from "zod";

// Shared field validators. Amounts are minor units (integer, non-negative).
const amount = z.number().int().nonnegative().max(99_999_999)
  .describe("Amount in minor units (e.g., £10 would be 1000)");
const currency = z.string().regex(/^[A-Z]{3}$/, "ISO 4217 alpha-3, uppercase (e.g. GBP)").default("GBP");
const httpsUrl = z.string().url();

export const hppSchema = z.object({
  amount,
  currency,
  narrative: z.string().max(24).optional()
    .describe("Statement narrative shown to the cardholder (max 24 chars). Defaults to 'MCP Payment'."),
});

export const paymentSchema = z.object({
  cardHolderName: z.string(),
  sessionHref: httpsUrl.describe("Sessions url from Checkout SDK (provide either a sessionHref or tokenHref, never both)").optional(),
  tokenHref: httpsUrl.describe("Token url from stored card (provide either a sessionHref or tokenHref, never both)").optional(),
  cvc: z.string().regex(/^\d{3,4}$/).describe("Optional CVC (Provide a value in cvcSessionHref or cvc, never both.)").optional(),
  cvcSessionHref: httpsUrl.describe("Optional CVC session url from Checkout SDK (Provide a value in cvcSessionHref or cvc, never both. Only supply if using tokenHref)").optional(),
  amount,
  currency,
  address1: z.string(),
  city: z.string(),
  postalCode: z.string().optional(),
  countryCode: z.string().regex(/^[A-Z]{2}$/, "ISO 3166-1 alpha-2, uppercase"),
  storeCard: z.boolean().default(false),
  createToken: z.boolean().default(false),
  channel: z.enum(["moto", "ecommerce", "recurring"]).default("moto")
    .describe("Payment channel. Defaults to 'moto'. Set 'ecommerce' for customer-present online flows."),
  narrative: z.string().max(24).optional()
    .describe("Statement narrative shown to the cardholder (max 24 chars). Defaults to 'MCP Payment'."),
  transactionReference: z.string().min(1).max(64).optional()
    .describe("Your unique reference for this payment. Reuse the same value to make a retry idempotent. Auto-generated when omitted."),
});


export const paymentDateQuerySchema = z.object({
  startDate: z
    .string()
    .optional()
    .describe(
      "Start date for the query in ISO 8601 format (YYYY-MM-DDTHH:MM:SSZ)"
    ),
  endDate: z
    .string()
    .optional()
    .describe(
      "End date for the query in ISO 8601 format (YYYY-MM-DDTHH:MM:SSZ)"
    ),
  pageSize: z.number().int().positive().max(499).optional().default(20),
});

export const paymentTxnRefQuerySchema = z.object({
  transactionReference: z
    .string()
    .optional()
    .describe(
      "Transaction reference to filter payments by"
    ),
  pageSize: z.number().int().positive().max(499).optional().default(20),
});

export const paymentIdQuerySchema = z.object({
  paymentId: z
    .string()
    .min(1)
    // Block path/query/fragment separators and whitespace (defence in depth;
    // the value is also encodeURIComponent'd before use). Deliberately permissive
    // on the character set so opaque Worldpay ids are not falsely rejected.
    .regex(/^[^\s/?#]+$/, "Payment id must not contain spaces or URL separators")
    .describe("Payment ID to retrieve")
});

export const manageSchema = z.object({
  commandName: z.string(),
  commandHref: httpsUrl
    .describe("The HAL action link returned in a prior payment response's _links (e.g. settle/cancel/refund). Must be a Worldpay URL."),
});


export const accountPayoutQuerySchema = z.object({
  narrative: z.string().optional().describe("Reference that may appear on beneficiary statements"),
  transactionReference: z.string().optional().describe("Unique reference for the payout"),
  accountNumber: z.string().optional().describe("Beneficiary bank account number"),
  payoutInstrumentId: z.string().optional().describe("A unique ID generated by Worldpay, holding the beneficiary bank details. You receive this in the response after successfully creating a payout instrument in the Parties API."),
  payoutInstrumentReference: z.string().optional().describe("A reference of the payoutInstrument created by you. This field holds the beneficiary bank details"),
  pageSize: z.number().int().positive().max(499).default(20),
  countryCode: z.string().optional().describe("ISO 3166-1 Alpha-2 country code of the payout destination"),
  pageNumber: z.number().int().positive().default(1),
  paymentState: z.enum(['AWAITING_EXECUTION', 'NEW', 'VALID', 'REJECTED','EXECUTED','COMPLETED','REVERSED','FAILED','INVALID']).optional(),
  startDate: z.string().optional().describe("Must be a Gregorian calendar date with ISO 8601 format YYYY-MM-DD"),
  endDate: z.string().optional().describe("Must be a Gregorian calendar date with ISO 8601 format YYYY-MM-DD"),
  payeeName: z.string().optional().describe("Complete payee name for the payout. This will be one of the following (depending on the beneficiary type): fullName - concatenated value from title + firstName + middleName + lastName; companyName"),
  sourceCurrency: z.string().optional().describe("Source ISO 4217 alpha-3 currency codes for the payout."),
  sourceAmount: z.number().optional().describe("Source amount. 18 digit precision including 2 decimal places"),
  targetCurrency: z.string().optional().describe("Target ISO 4217 alpha-3 currency codes for the payout."),
  targetAmount: z.number().optional().describe("18 digit precision including 2 decimal places"),
});


export const delegateTokenSchema = z.object({
  payment_method: z.object({
    type: z.enum(["card"]).describe("Payment method type"),
    // Network tokens only. Raw PANs (fpan) are not accepted on this MCP surface:
    // a PAN passed as a tool argument would transit the model context and any
    // transcript/log, dragging the whole pipeline into PCI-DSS scope.
    card_number_type: z.enum(["network_token"]).describe("Only network tokens are accepted (no raw card numbers)"),
    number: z.string().describe("Network token value"),
    exp_month: z.string().optional().describe("Expiration month"),
    exp_year: z.string().optional().describe("Expiration year"),
    name: z.string().optional().describe("Cardholder name"),
    cryptogram: z.string().optional().describe("Network token cryptogram"),
    eci_value: z.string().optional().describe("Electronic Commerce Indicator value"),
    checks_performed: z.array(z.enum(["avs", "cvv", "ani", "auth0"])).optional().describe("Checks performed on the payment method"),
    iin: z.string().optional().describe("Issuer identification number"),
    display_card_funding_type: z.enum(["credit", "debit", "prepaid"]).describe("Card funding type for display"),
    display_wallet_type: z.string().optional().describe("Wallet type for display"),
    display_brand: z.string().optional().describe("Card brand for display"),
    display_last4: z.string().optional().describe("Last 4 digits for display"),
    metadata: z.object({}).describe("Payment method metadata")
  }).describe("Payment method details"),

  allowance: z.object({
    reason: z.enum(["one_time"]).describe("Reason for the allowance"),
    max_amount: z.number().int().nonnegative().describe("Maximum amount in minor units (e.g., $20 → 2000)"),
    currency: z.string().regex(/^[a-z]{3}$/, "ISO-4217 lowercase currency code (e.g., usd)").describe("ISO-4217 lowercase currency code (e.g., usd)"),
    checkout_session_id: z.string().describe("Checkout session identifier"),
    merchant_id: z.string().describe("Merchant identifier. This should be retrieved from the Merchant who will process the payment"),
    expires_at: z.string().describe("Expiration timestamp")
  }).describe("Allowance constraints for the delegated token"),

  billing_address: z.object({
    line_one: z.string().describe("First line of billing address"),
    line_two: z.string().optional().describe("Second line of billing address"),
    city: z.string().describe("Billing address city"),
    state: z.string().describe("Billing address state"),
    country: z.string().regex(/^[A-Z]{2}$/).describe("ISO-3166-1 alpha-2 country code"),
    postal_code: z.string().describe("Billing address postal code")
  }).optional().describe("Billing address information"),

  risk_signals: z.array(z.object({
    score: z.number().describe("Risk score"),
    action: z.enum(["blocked", "manual_review", "authorized"]).describe("Risk action taken")
  })).describe("Risk assessment signals"),

  metadata: z.object({}).describe("Additional metadata for the delegate token")
});
